# Generated by Django 6.0.1 on 2026-01-17 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('description', models.CharField(max_length=200, verbose_name='Description/Purpose')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
                ('access_level', models.CharField(choices=[('Full Access', 'Full Access'), ('Limited Access', 'Limited Access'), ('Read Only', 'Read Only'), ('API Only', 'API Only')], default='Full Access', max_length=20)),
                ('allowed_roles', models.JSONField(blank=True, default=list, verbose_name='Allowed Roles (leave empty for all)')),
                ('allowed_days', models.JSONField(blank=True, default=list, verbose_name='Allowed Days (0=Monday, 1=Tuesday, etc.)')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Access Start Time')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Access End Time')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('isp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Internet Service Provider')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Access Time')),
                ('total_access_count', models.IntegerField(default=0, verbose_name='Total Access Count')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('require_2fa', models.BooleanField(default=False, verbose_name='Require 2FA')),
                ('notify_on_access', models.BooleanField(default=False, verbose_name='Notify on Access')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ip_whitelists', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitelisted_ips', to=settings.AUTH_USER_MODEL, verbose_name='Associated User')),
            ],
            options={
                'verbose_name': 'IP Whitelist',
                'verbose_name_plural': 'IP Whitelist',
                'ordering': ['ip_address'],
                'indexes': [models.Index(fields=['ip_address'], name='school_app__ip_addr_ba8bcb_idx'), models.Index(fields=['status'], name='school_app__status_fbe4e7_idx'), models.Index(fields=['user'], name='school_app__user_id_73e5b2_idx')],
            },
        ),
    ]
